spring:
  profiles:
    active: sqlite
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
server.port: 8080
sosha:
  jwt-expiry-hours: 8
  secret-file: ${user.home}/.sosha/secret.key
encryption:
  sqlite-cipher-key: ${SOSHA_CIPHER_KEY:sosha-demo-key-256bit}
  pg-crypto-password: ${SOSHA_PG_PASS:sosha-demo-pass}
  encryption-algorithm: AES-256-GCM
