spring:
  datasource:
    url: jdbc:sqlite:${user.home}/.sosha/sosha.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect
    hibernate.ddl-auto: update
  flyway:
    enabled: false
    validate-on-migrate: false
